setup: Move items from lib/setup to setup
Now that there's no longer more than one setup script, and there's very
little in scripts/lib/setup to begin with, it seems better to just
reabsorb URLP_PLATFORM and urlp.npm_install into script/setup. That
said, the urlp.npm_install implementation may make sense to include in a
go-script-bash module for the reasons stated in its function comments,
namely that file streams are managed differently on Windows, and npm can
be pretty noisy anyway.

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -2,7 +2,8 @@
 #
 # Runs first-time setup commands for a freshly-cloned repository
 
-. "$_GO_USE_MODULES" 'setup'
+export URLP_PLATFORM="${URLP_PLATFORM:-$(node -e \
+  'console.log(process.platform)')}"
 
 urlp.check_for_prerequisite_tools() {
   if ! command -v node >/dev/null; then
@@ -12,6 +13,22 @@ urlp.check_for_prerequisite_tools() {
     ! command -v redis-server >/dev/null; then
     @go.printf 'Please install redis-server before continuing.\n' >&2
     return 1
+  fi
+}
+
+# Some Node.js processes hang on Windows, most notably NPM, due to the way file
+# descriptors that reference the terminal are managed. On top of that, npm can
+# be rather noisy. Consequently, we save all output to a file for consistency
+# across platforms.
+urlp.npm_install() {
+  local npm_log="$_GO_ROOTDIR/npm.log"
+
+  if ! npm install -q --no-progress "$@" >"$npm_log" 2>&1; then
+    @go.log ERROR "npm install failed (from $npm_log):"
+    printf '%s\n' "$(< "$npm_log")" >&2
+    return '1'
+  else
+    rm "$npm_log"
   fi
 }
 
