test: Make Coveralls, Code Climate branch URLs
More specific than the generic top-level URLs.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -43,6 +43,8 @@ declare GITHUB_REPO="$(git config --show remote.origin.url)"
 GITHUB_REPO="${GITHUB_REPO##*@github.com:}"
 GITHUB_REPO="${GITHUB_REPO%.git}"
 
+declare GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+
 _test_mocha_flags() {
   local flag_line_pattern='^ *-'
   local line
@@ -169,15 +171,15 @@ _test_coverage() {
       return 1
     fi
     printf 'Coverage report sent to Coveralls: %s' \
-      "https://coveralls.io/github/$GITHUB_REPO"
+      "https://coveralls.io/github/${GITHUB_REPO}?branch=${GIT_BRANCH}"
 
     if [[ -n "$CODECLIMATE_REPO_TOKEN" ]]; then
       if ! codeclimate-test-reporter < "$lcov_info_path"; then
-        echo 'Failed to send coverage report to Code Climate.' >&2
+        echo 'Failed to send report to Code Climate.' >&2
         return 1
       fi
-      printf 'Coverage report sent to Code Climate: %s' \
-        "https://codeclimate.com/github/$GITHUB_REPO"
+      printf 'Report sent to Code Climate: %s' \
+        "https://codeclimate.com/github/${GITHUB_REPO}/compare/${GIT_BRANCH}"
     fi
   fi
   return "$result"
